rails-example/config/routes.rb
Rails.application.routes.draw do
  get 'tests/new'
  devise_for :users
  resources :users, :only => [:show]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "exercises#index"

  resources :tests do
    resources :user_answers
  end
  
  resources :exercises, only: [:show, :edit, :update, :destroy, :new, :create]  do
    resources :answers 
    resources :user_answers #, only: [ :new, :create ]
    
    
    collection do
      get :category_filter
      get :exercise_user_answer_form
    end

  end
end

rails-example/app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :exercise
  has_many :user_answers, dependent: :destroy
end

rails-example/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

rails-example/app/models/exercise.rb
class Exercise < ApplicationRecord
    has_many :answers, dependent: :destroy
    has_many :user_answers, dependent: :destroy
    belongs_to :tests


    accepts_nested_attributes_for :answers, :user_answers
end

def next
    Exercise.first(:conditions => ['id > ?', self.id], :order => 'id ASC')
  end

rails-example/app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user, required: true, autosave: true
end

rails-example/app/models/test.rb
class Test < ApplicationRecord
  has_many :exercises
  has_many :user_answers
end

rails-example/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_answers, dependent: :destroy
  
end

rails-example/app/models/user_answer.rb
class UserAnswer < ApplicationRecord
    belongs_to :exercise
    belongs_to :answer
    belongs_to :user

    after_create_commit {
        broadcast_replace(partial: "user_answers/solution", locals: { user_answer: self })
    }
end

rails-example/app/controllers/answers_controller.rb
class AnswersController < ApplicationController
    before_action :get_exercise

    def index
        # @exercise = Exercise.find(params[:exercise_id])

        #@answers = Answer.where(exercise: params[:exercise]
        @answers = @exercise.answers
    end


    private

    def get_exercise
        @exercise = Exercise.find(params[:id])
      end

    def answer_params
        params.require(:answer).permit(:answer, :true_answer)
    end
      
end

rails-example/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    def configure_permitted_parameters
      # For additional fields in app/views/devise/registrations/new.html.erb
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  
      # For additional in app/views/devise/registrations/edit.html.erb
      devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
    end

end

rails-example/app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
    # skip_before_action: authenticate_user!, only: :index
    before_action :set_exercise, only: [:show, :edit, :update, :destroy]

    def index
      @exercises = Exercise.all

      @categories = @exercises.map { |exercise| exercise['category'] }.uniq
    end

    def show
      @user_answer = UserAnswer.new(exercise_id: @exercise.id)
      @answers = @exercise.answers
      # redirect_to new_exercise_user_answer_path(@exercise)
      
    end
    
    def new
        @exercise = Exercise.new # needed to instantiate the form_for
    end

    def create
        @exercise = Exercise.new(exercise_params)
        @exercise.save

        # no need for app/views/exercises/create.html.erb
        redirect_to exercise_path(@exercise)
      end

    def edit
      # @user_answer = UserAnswer.new  
    end
    
    def update
      # @exercise.update(exercise_params)
      # @user_answer = UserAnswer.new(exercise_id: @exercise.id, answer_id: @answer.id)
      # raise
      redirect_to exercise_path(@exercise)

    end
    
    def destroy

        @exercise.destroy
    
        # no need for app/views/exercises/destroy.html.erb
        redirect_to exercises_path()
      end
    
    def category_filter

      @exercises = Exercise.where(category: params[:category])
      
    end

    def exercise_user_answer_form
      @exercise = Exercise.find(params[:exercise_id])
      @user_answer = UserAnswer.new(exercise_id: @exercise.id)

    end

    private

    def set_exercise
        @exercise = Exercise.find(params[:id])
      end
    

    def exercise_params
        params.require(:exercise).permit(:id, :answers, :answer_id, :category, :number, :statement, :user_answers)
    end
    
  end
  

rails-example/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
end

rails-example/app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :test_params
  
  def new
    # We need @restaurant in our `simple_form_for`
    @user_answers = current_user.user_answers
    @failed_answers = @user_answers.map {|user_answer| user_answer.exercise.answers.select {|answer| answer.true_answer == false && answer.id == user_answer.answer_id}}.flatten
    @failed_exercises = @failed_answers.map {|answer| answer.exercise}.uniq

    @user_answer = UserAnswer.new()
    @test = Test.new(user_answer: @user_answer)
  end

  def create
    @test = Test.new(test_params)
  end

  private    

    def test_params
        params.permit(:id, :test, :exercises, :exercise_id, :user_id, :answers)
    end
end

rails-example/app/controllers/user_answers_controller.rb
class UserAnswersController < ApplicationController
    before_action :user_answer_params

    def new
        @exercise = Exercise.find(params[:exercise_id])
        @answers = Exercise.find(params[:exercise_id]).answers
        @user_answer = UserAnswer.new(exercise_id: @exercise.id)    
    end
    

    def create
        @user_answer = UserAnswer.new(user_answer_params)
        @answers = Exercise.find(params[:exercise_id]).answers
        @exercise = Exercise.find(params[:exercise_id])
        @user_answer.exercise = @exercise
        
        if @exercise.multiple_choice?
            @user_answer.answer = @exercise.answers.find(params[:answer])
        else
            @user_answer.answer = Answer.new(answer: params[:answer], exercise_id: @exercise.id)
        end

        @user_answer.user_id = current_user.id
        @user_answer.save
        
        respond_to do |format|
            format.html { redirect_to @exercise, notice: "Quote was successfully destroyed." }
            format.turbo_stream
        end         
    end

    private

    def user_answer_params
        params.permit(:exercise_id, :answer_id, :user_answer, :user_id)
    end

end

rails-example/app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_same_user, only: [:show, :edit, :update, :destroy]

    def show
        # find user id
        @user = User.find(params[:id])

        # paginate user_answers of the Historic table
        @user_answers_ordered = @user.user_answers.order(updated_at: :desc)
        @user_answers= @user_answers_ordered.page(params[:page]).per(10)

        # create user_answers dict with dates of when he did the exercises and their scores
        @user_answer_dates = @user.user_answers.map{|user_answer| user_answer.created_at.to_date}
        @user_answer_scores = @user.user_answers.map{|user_answer| user_answer.answer}.map{|answer| answer.true_answer}
        @user_answer_scores = @user_answer_scores.map{|score| score ? 1:0}
        @user_answer_scores_dict = Hash[@user_answer_dates.zip(@user_answer_scores)]
    end

    def require_same_user
        # raise
        if current_user.id.to_s != params[:id]
          redirect_to root_path, alert: "Access Denied!"
        end  
    end
      
end

rails-example/app/helpers/answers_helper.rb
module AnswersHelper
end

rails-example/app/helpers/application_helper.rb
module ApplicationHelper
end

rails-example/app/helpers/profiles_helper.rb
module ProfilesHelper
end

rails-example/app/helpers/tests_helper.rb
module TestsHelper
end

rails-example/app/helpers/user_answers_helper.rb
module UserAnswersHelper
end

rails-example/app/helpers/useranswers_helper.rb
module UseranswersHelper
end

rails-example/app/helpers/users_helper.rb
module UsersHelper
end

rails-example/app/views/exercises/_exercise.html.erb
  <div class="exercise-statement col-xs-12 col-sm-12 col-lg-8 mx-auto">
    <div class="card">

      <% if @exercise.image %>
        <%= image_tag @exercise.image, class: "mx-auto image-centered", width: 300, height: 350%>
        <p class="exercise-source text-center text-muted">Fonte: <%=@exercise.source%></p>
        <div class="card-body text-justify"> 
          <%= simple_format @exercise.statement %>
        </div>

      <% else %>
        <div class="card-body text-justify"> 
          <%= simple_format @exercise.statement %>
        </div>
        <p class="exercise-source text-center text-muted">Fonte: <%=@exercise.source%></p>
      <% end %> 

    </div>
  </div>

rails-example/app/views/exercises/category_filter.html.erb
<div class="container">
    <ul>
        <% @exercises.each do |exercise| %>
            <li><%=link_to "Exercício nº #{exercise.exercise_number} - #{exercise.category}", exercise_path(exercise) %></li>
        <%end%>
    </ul>
<br>

rails-example/app/views/exercises/index.html.erb
<!-- BANNER -->
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.viewsonic.com/library/wp-content/uploads/2019/12/Technology-in-the-Classroom.jpg);">
  <div class="container">
    <h1>Prepara-te para os Exames!</h1>
    <p>Começa a usar o site e a aprender!</p>
    <div class="vertical-center">
        <button type="button" class="btn btn btn-outline-warning my-2 my-sm-0">Começar a Aprender!</button>
    </div>
  </div>
</div>

<!-- Cards para os exercícios -->
<% if @exercises.empty? %>
    <p>No exercises yet.</p>
<% else %>
<br>
<br>
    <div class="container">
        <div class="row row-cols-1 row-cols-md-3 g-4 justify-content-center">
            <% @categories.each do |category| %> 
                <div class="col">
                    <%= link_to category_filter_exercises_path(:category => category), class: "card_link" do%>
                        <div class="card">
                            <img src="https://i0.wp.com/www.vozprof.com/wp-content/uploads/2020/12/matematica.jpg?fit=930%2C450&ssl=1" class="card-img-top" alt="...">
                            <div class="card-body">
                                <p class="card-text">Lista de exercícios de <%=category%>. Clica aqui para ires para os exercícios!</p>

                                <button class='btn btn-outline-info my-2 my-sm-0 w-100'><%=category%></button>
                            </div>
                        </div>
                    <% end %>
                </div>
            <% end %>
        </div>
    </div>
<% end %>

<%#= link_to 'Create New Exercise', new_exercise_path %>
<%#= link_to 'Do a test', new_test_user_answer_path() %>

rails-example/app/views/exercises/not_used/_form.html.erb
<%= simple_form_for(@exercise) do |f| %>
    <%= f.input :category %>
    <%= f.input :statement %>
    <%= f.input :number %>
    <%= f.input :answers %>
    <%= f.input :true_answer %>
    <%= f.submit %>
<% end %>

rails-example/app/views/exercises/not_used/edit.html.erb
<%= simple_form_for [@exercise], wrapper: :inline_form, :html=> { class: 'form-check form-inline' } do |f| %>
    <%= f.input_field :answers, 
        label: '',
        as: :radio_buttons, 
        class: 'form-check-input',
        collection: @exercise.answers.collect {|u| [u.answer] }%>
    <%= f.submit 'Submit Answer!', class: "btn btn-outline-success" %>
<% end %>

rails-example/app/views/exercises/not_used/exercise_user_answer_form.html.erb
<%= simple_form_for [@exercise, @user_answer], new_exercise_user_answer_path(@exercise), wrapper: :inline_form, :html=> { class: 'form-check form-inline' } do |f| %>
    <%= f.input_field :answer_id, 
        label: '',
        as: :radio_buttons, 
        class: 'form-check-input',
        collection: @exercise.answers.collect {|u| [u.answer] }%>
    <%= f.submit 'Submit Answer!', class: "btn btn-outline-success" %>
<% end %>

rails-example/app/views/exercises/not_used/new.html.erb
<%= render "form", exercise: @exercise %>

rails-example/app/views/exercises/show.html.erb
<div class="container exercise-page">
  <%# Title %>
  <h2 class="exercise-title">
    Exercício <%= @exercise.id %> de <%= @exercise.category %> - <%= @exercise.sub_category %>
  </h2>

  <%# Problema, Imagem e Fonte %>
  <%= render 'exercise', exercise: @exercise %>

  <br>
    <%# UserAnswer Form %>
    <%= render 'user_answers/user_answer_form', user_answer: @user_answer %>
  <br>

    <%# Resolução e Confirmação de certo ou errado%>
  <%= turbo_frame_tag "solution" %>

</div>

rails-example/app/views/user_answers/_solution.html.erb
<%= turbo_frame_tag @user_answer do %>
  <p>A tua resposta: <%=user_answer.answer.answer%></p>
  
  <%if user_answer.answer.answer == user_answer.exercise.answers.select { |answer| answer.true_answer == true }[0].answer %>
    <p>A tua resposta está correta!</p>
  <%else%>
    <p>A tua resposta está errada.</p>
  <%end%>

  <br>
  <h3>Resolução do Exercício:</h3>
  <br>

  <div class="user_answer.-statement col-xs-9 col-sm-9 col-lg-6 mx-auto">    
    <%= simple_format user_answer.exercise.resolution %>
  </div>

  <br>
  <%= link_to "Go back to Home Page", exercises_path() %>
  <br>
<%end%> 

rails-example/app/views/user_answers/_user_answer_form.html.erb
<%if @exercise.multiple_choice%>
  <%= simple_form_for [@exercise, @user_answer], authenticity_token: true, remote: true, :html=> { class: 'col-xs-12 col-sm-12 col-lg-3 mx-auto text-center list-group', id:"form"} do |f| %>
      <%= f.simple_fields_for :answers, include_id: false do |answer| %>
        <%= f.input_field :answer, 
            label: 'Answer',
            as: :radio_buttons,
            class: 'form-check-input',
            :item_label_class => 'list-group-item',
            name: 'answer',
            collection: @answers, label_method: :answer %>
            <br>
        <%= f.submit 'Submit Answer!', class: "btn btn-outline-success", id: "submit", data: { turbo_frame: dom_id(@user_answer) } %>
      <% end %>
  <% end %>
  <%else%>
    <%= simple_form_for [@exercise, @user_answer], authenticity_token: true, remote:true, :html=> { class: 'col-xs-12 col-sm-12 col-lg-3 mx-auto text-center list-group' } do |f| %>
      <%=f.input :answer, as: :text %>
      <%= f.submit 'Submit Answer!', class: "btn btn-outline-success" %>
    <% end %>
<% end %>

rails-example/app/views/user_answers/create.turbo_stream.erb
<%= turbo_stream.update "solution", partial: "user_answers/solution", locals: { user_answer: @user_answer } %>
<%= turbo_stream.update UserAnswer.new, "" %>

rails-example/app/views/user_answers/not_used/new.html.erb
<div class="container exercise-page">
  <h2 class="exercise-title">Exercício <%= @exercise.id %> de <%= @exercise.category %> - <%= @exercise.sub_category %></h2>

  <div class="exercise-statement col-xs-12 col-sm-12 col-lg-8 mx-auto">
    <div class="card">
    <% if @exercise.image %>
      <%= image_tag @exercise.image, class: "mx-auto image-centered", width: 300, height: 350%>
      <p class="exercise-source text-center text-muted">Fonte: <%=@exercise.source%></p>
      <div class="card-body text-justify"> 
        <%= simple_format @exercise.statement %>
      </div>
    <% else %>
      <div class="card-body text-justify"> 
        <%= simple_format @exercise.statement %>
      </div>
      <p class="exercise-source text-center text-muted">Fonte: <%=@exercise.source%></p>
    <% end %> 
    </div>
  </div>

  <br>

  <%= render 'user_answer_form'%>


  <br>
  <div id="resolution" style="display: none;">
    <%= render 'solution'%>
  </div>
</div>
<%# <%raise%> 

<script>

document.querySelector("#form").addEventListener("submit", (e)=>{
  // e.preventDefault();
  answer = document.querySelector('input[name="answer"]:checked').value;
  console.log(answer)
  var array = [1, 2, 3, 4, 5];
  document.getElementById("resolution").style.display = 'block';

});
</script> 
// <%# <%raise%> 

// <%# <script>

// var myEl = document.getElementById('submit');

// myEl.addEventListener('click', function() {
//     document.getElementById("resolution").style.display = 'block';
// }, false);

// </script> %>

rails-example/app/views/users/_table.html.erb
<div class="table-responsive">
  <table class="table caption-top" id="previous-exercises-table">
  <caption class="text-center"><h5>Histórico de Respostas</h4></caption>
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Imagem</th>
        <th scope="col">Categoria</th>
        <th scope="col">Pergunta</th>
        <th scope="col"># Errado</th>
        <th scope="col">Última Tentativa</th>
      </tr>
    </thead>
    <tbody>
    <% @user_answers.each do |user_answer|%>
      <tr>
        <td><%=link_to user_answer.exercise.id, new_exercise_user_answer_path(user_answer.exercise)%></td>
        <td>
          <%if user_answer.exercise.image%>
            <%=link_to image_tag(user_answer.exercise.image,  class: "mx-auto exercise-image", width: "100", height: "100"), new_exercise_user_answer_path(user_answer.exercise)%>
          <%else%>
            None
          <%end%>
        </td>
        
        <td><%=link_to user_answer.exercise.category, new_exercise_user_answer_path(user_answer.exercise)%></td>
        <td><%=link_to user_answer.exercise.statement, new_exercise_user_answer_path(user_answer.exercise)%></td>
        <td><%=user_answer.user.user_answers.find_all{
          |answer_user| (answer_user.answer.true_answer== false) && 
          (answer_user.exercise_id == user_answer.exercise.id)
          }.count%></td>

        <% if user_answer.answer_id == user_answer.exercise.answers.select { |answer| answer.true_answer == true }[0].id%>
          <td>✅</td>
        <%else%>
          <td>❌</td>
        <%end%>
      </tr>
      <%end%>
    </tbody>
  </table>
  </div>

rails-example/app/views/users/show.html.erb
<script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap5.min.js"></script>

<section>
  <div class="container py-5">
    <%# <div class="row">
      <div class="col">
        <nav aria-label="breadcrumb" class="bg-light rounded-3 p-3 mb-4">
          <ol class="breadcrumb mb-0">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item"><a href="#">User</a></li>
            <li class="breadcrumb-item active" aria-current="page">User Profile</li>
          </ol>
        </nav>
      </div>
    </div> %>

    <div class="row">
      <div class="col-lg-4">
        <div class="card mb-4">
          <div class="card-body text-center">
            <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava3.webp" alt="avatar"
              class="rounded-circle img-fluid" style="width: 150px;">
            <h5 class="my-3"><%= @user.first_name %> <%= @user.last_name %></h5>
            <p class="text-muted mb-1">Aluno do Secundário</p>
            <p class="text-muted mb-4">Lisboa, Portugal</p>
            <%# <div class="d-flex justify-content-center mb-2">
              <button type="button" class="btn btn-primary">Follow</button>
              <button type="button" class="btn btn-outline-primary ms-1">Message</button>
            </div> %>
          </div>
        </div>
        <div class="card mb-4 mb-lg-0">
          <div class="card-body p-0">
            <ul class="list-group list-group-flush rounded-3">
              <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                <i class="fas fa-globe fa-lg text-warning"></i>
                <p class="mb-0">https://mdbootstrap.com</p>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                <i class="fab fa-github fa-lg" style="color: #333333;"></i>
                <p class="mb-0">mdbootstrap</p>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                <i class="fab fa-twitter fa-lg" style="color: #55acee;"></i>
                <p class="mb-0">@mdbootstrap</p>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                <i class="fab fa-instagram fa-lg" style="color: #ac2bac;"></i>
                <p class="mb-0">mdbootstrap</p>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                <i class="fab fa-facebook-f fa-lg" style="color: #3b5998;"></i>
                <p class="mb-0">mdbootstrap</p>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-lg-8">
        <div class="card mb-4">
          <div class="card-body">
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Full Name</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @user.first_name %> <%= @user.last_name %></p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Email</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @user.email %></p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Address</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">Lisboa, Portugal</p>
              </div>
            </div>
          </div>
        </div>
        
        <div class="row">
          <div class="col-md-6">
            <div class="card mb-4 mb-md-0">
              <div class="card-body">
                <p class="mb-4"><span class="text-primary font-italic me-1">assigment</span> Project Status
                </p>
                <p class="mb-1" style="font-size: .77rem;">Web Design</p>
                <div class="progress rounded" style="height: 5px;">
                  <div class="progress-bar" role="progressbar" style="width: 80%" aria-valuenow="80"
                    aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <p class="mt-4 mb-1" style="font-size: .77rem;">Website Markup</p>
                <div class="progress rounded" style="height: 5px;">
                  <div class="progress-bar" role="progressbar" style="width: 72%" aria-valuenow="72"
                    aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <p class="mt-4 mb-1" style="font-size: .77rem;">One Page</p>
                <div class="progress rounded" style="height: 5px;">
                  <div class="progress-bar" role="progressbar" style="width: 89%" aria-valuenow="89"
                    aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <p class="mt-4 mb-1" style="font-size: .77rem;">Mobile Template</p>
                <div class="progress rounded" style="height: 5px;">
                  <div class="progress-bar" role="progressbar" style="width: 55%" aria-valuenow="55"
                    aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <p class="mt-4 mb-1" style="font-size: .77rem;">Backend API</p>
                <div class="progress rounded mb-2" style="height: 5px;">
                  <div class="progress-bar" role="progressbar" style="width: 66%" aria-valuenow="66"
                    aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </div>
            </div>
          </div>


          <div class="col-md-6">
            <div class="card mb-4 mb-md-0">
              <div class="card-body">
                <p class="mb-4"><span class="text-primary font-italic me-1">assigment</span> Project Status
                </p>
                
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<%# <div class="col-md-6"> %>
<!--<canvas id="lineChart" width="500" height="500" data-dates="<%=@user_answer_dates %>" data-scores="<%=@user_answer_scores %>"></canvas> %>-->
<%# </div> %>

  <%= 
      paginate @user_answers, 
      theme: "bootstrap-5", 
      pagination_class: "pagination flex-wrap justify-content-center"
  %>

<div class="container">
  <%= page_entries_info @user_answers %>
  <%= render 'table', user_answers: @user_answers %>
</div>

  <%= 
      paginate @user_answers, 
      theme: "bootstrap-5", 
      pagination_class: "pagination flex-wrap justify-content-center"
  %>

<script>
// Data for Line Chart
var userAnswers = document.getElementById('lineChart');
const dates = userAnswers.dataset.dates;
const high_prices_spot = userAnswers.dataset.scores;
console.log(dates)
console.log(high_prices_spot)

const data = {
    labels: dates,
    datasets: [ {
            label: 'User Score',
            backgroundColor: 'rgb(0, 0, 255)',
            borderColor: 'rgb(0, 0, 255)',
            data: high_prices_spot
        }]
};

const config_line = {
    type: 'line',
    data: data,
    options: {
        responsive: false,
        plugins: {
            legend: {
                position: 'top'
            },
            title: {
                display: true,
                text: 'Stock High Price Comparison'
            }
        }
    }
};

const myLineChart = new Chart(document.getElementById('lineChart'), config_line);
// var xyValues = [
//   {x:50, y:7},
//   {x:60, y:8},
//   {x:70, y:8},
//   {x:80, y:9},
//   {x:90, y:9},
//   {x:100, y:9},
//   {x:110, y:10},
//   {x:120, y:11},
//   {x:130, y:14},
//   {x:140, y:14},
//   {x:150, y:15}
// ];
// new Chart("myChart", {
//   type: "scatter",
//   data: {
//     datasets: [{
//       pointRadius: 4,
//       pointBackgroundColor: "rgba(0,0,255,1)",
//       data: xyValues
//     }]
//   },
// });


  </script>